// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: user_notification_event.proto

package notification_event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlanManagementNotificationEvent struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UserId                string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanId                string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	NotificationEventType string                 `protobuf:"bytes,3,opt,name=notification_event_type,json=notificationEventType,proto3" json:"notification_event_type,omitempty"`
	Payload               *structpb.Struct       `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PlanManagementNotificationEvent) Reset() {
	*x = PlanManagementNotificationEvent{}
	mi := &file_user_notification_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanManagementNotificationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanManagementNotificationEvent) ProtoMessage() {}

func (x *PlanManagementNotificationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_user_notification_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanManagementNotificationEvent.ProtoReflect.Descriptor instead.
func (*PlanManagementNotificationEvent) Descriptor() ([]byte, []int) {
	return file_user_notification_event_proto_rawDescGZIP(), []int{0}
}

func (x *PlanManagementNotificationEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlanManagementNotificationEvent) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *PlanManagementNotificationEvent) GetNotificationEventType() string {
	if x != nil {
		return x.NotificationEventType
	}
	return ""
}

func (x *PlanManagementNotificationEvent) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_user_notification_event_proto protoreflect.FileDescriptor

const file_user_notification_event_proto_rawDesc = "" +
	"\n" +
	"\x1duser_notification_event.proto\x12\x12notification_event\x1a\x1cgoogle/protobuf/struct.proto\"\xbe\x01\n" +
	"\x1fPlanManagementNotificationEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x126\n" +
	"\x17notification_event_type\x18\x03 \x01(\tR\x15notificationEventType\x121\n" +
	"\apayload\x18\x04 \x01(\v2\x17.google.protobuf.StructR\apayloadB6Z4nyihtuun.com/bentosystem/protobuf/notification_eventb\x06proto3"

var (
	file_user_notification_event_proto_rawDescOnce sync.Once
	file_user_notification_event_proto_rawDescData []byte
)

func file_user_notification_event_proto_rawDescGZIP() []byte {
	file_user_notification_event_proto_rawDescOnce.Do(func() {
		file_user_notification_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_notification_event_proto_rawDesc), len(file_user_notification_event_proto_rawDesc)))
	})
	return file_user_notification_event_proto_rawDescData
}

var file_user_notification_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_user_notification_event_proto_goTypes = []any{
	(*PlanManagementNotificationEvent)(nil), // 0: notification_event.PlanManagementNotificationEvent
	(*structpb.Struct)(nil),                 // 1: google.protobuf.Struct
}
var file_user_notification_event_proto_depIdxs = []int32{
	1, // 0: notification_event.PlanManagementNotificationEvent.payload:type_name -> google.protobuf.Struct
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_notification_event_proto_init() }
func file_user_notification_event_proto_init() {
	if File_user_notification_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_notification_event_proto_rawDesc), len(file_user_notification_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_notification_event_proto_goTypes,
		DependencyIndexes: file_user_notification_event_proto_depIdxs,
		MessageInfos:      file_user_notification_event_proto_msgTypes,
	}.Build()
	File_user_notification_event_proto = out.File
	file_user_notification_event_proto_goTypes = nil
	file_user_notification_event_proto_depIdxs = nil
}
