spring:
  jpa:
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: user
    create-schemas: true
  datasource:
    driver-class-name: org.postgresql.Driver
#      data-locations: classpath:data-dev.sql

logging:
  level:
    com.nyihtuun.bentosystem.userservice: INFO

aws:
  region: ap-northeast-1
  bucket-name: bento-saas-dev
  user-image-folder: bento_images/user/
  expiration-time-min: 60
