spring:
  jpa:
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: planmanagement
    create-schemas: true
  datasource:
    driver-class-name: org.postgresql.Driver

logging:
  level:
    com.nyihtuun.bentosystem.planmanagementservice: INFO

plan-management:
  max-page-size: ${PLAN_MAX_PAGE_SIZE:8}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration-time: ${JWT_EXPIRATION_TIME}

aws:
  region: ${AWS_REGION}
  bucket-name: ${AWS_BUCKET_NAME}
  plan-image-folder: bento_images/plan/
  plan-meal-image-folder: bento_images/meal/
  expiration-time-min: ${AWS_EXPIRATION_TIME_MIN}