spring:
  jpa:
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/bento_saas?currentSchema=planmanagement,public
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      separator: ^^
      schema-locations: classpath:init-schema.sql

logging:
  level:
    com.nyihtuun.bentosystem.planmanagementservice: INFO

plan-management:
  max-page-size: ${PLAN_MAX_PAGE_SIZE:8}
