spring:
  application:
    name: subscription-service
  messages:
    basename: messages
    encoding: UTF-8

server:
  port: 4001
  servlet:
    context-path: /subscription

grpc:
  server:
    port: 9001