spring:
  application:
    name: user-service
  messages:
    basename: messages
    encoding: UTF-8

server:
  port: 4004
  servlet:
    context-path: /user

login:
  path: /auth/login

security:
  messages:
    login_success: "Login success"
    bad_credentials: "Bad credentials"
    auth_failed: "Authentication failed"