spring:
  jpa:
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: subscription
    create-schemas: true
  datasource:
    driver-class-name: org.postgresql.Driver

logging:
  level:
    com.nyihtuun.bentosystem.subscriptionservice: INFO

subscription:
  plan-management-service-url: ${PLAN_MANAGEMENT_SERVICE_URL}
  plan-management-version: v1
  plan-management-plan-details-path: plan
  connect-timeout-seconds: 5
  read-timeout-seconds: 5


resilience4j:
  circuitbreaker:
    instances:
      plan-management-service:
        failureRateThreshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

  retry:
    instances:
      plan-management-service:
        maxAttempts: 3
        waitDuration: 300ms

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration-time: ${JWT_EXPIRATION_TIME}