db-params:
  url: postgres://postgres:admin@localhost:5432/bento_saas?sslmode=disable&search_path=notification
kafka-params:
  bootstrap-servers:
    - localhost:9092
  partition: 0
  topic-name: user-notification-topic
  group-id: notification-service
server-address: localhost
server-port: 4005
jwt-secret: 3419307D818FD3B5F382094D0598DC6F83C4E969268F0B412542B01DF3847A46
cleanup-cron: "*/3 * * * *"