#db-params:
#  url: postgres://postgres:admin@localhost:5432/bento_saas?sslmode=disable&search_path=notification
db-params:
  user: ${NOTI_DB_PARAMS_USER}
  password: ${NOTI_DB_PARAMS_PASSWORD}
  address: ${NOTI_DB_PARAMS_ADDRESS}
  port: ${NOTI_DB_PARAMS_PORT}
  dbname: ${NOTI_DB_PARAMS_DBNAME}
kafka-params:
  bootstrap-servers:
    - ${NOTI_KAFKA_PARAMS_BOOTSTRAP_SERVERS}
  topic-name: user-notification-topic
  group-id: notification-service
server-address: ${NOTI_SERVER_ADDRESS}
server-port: 4005
jwt-secret: ${JWT_SECRET}
cleanup-cron: "0 0 * * SUN"