spring:
  application:
    name: plan-management-service
  messages:
    basename: messages
    encoding: UTF-8
  jpa:
    properties:
      hibernate:
        type:
          json_format_mapper: jackson

server:
  port: 4000
  servlet:
    context-path: /plan-management

grpc:
  server:
    port: 9000

plan-management:
  scheduler-cron: "0 0 0 1 * ?"
  zone: Asia/Tokyo
