spring:
  application:
    name: plan-management-service
  messages:
    basename: messages
    encoding: UTF-8
  datasource:
    url: jdbc:postgresql://localhost:5432/bento_saas
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
server:
  port: 4000
  servlet:
    context-path: /plan-management
