spring:
  application:
    name: invoice-service
  messages:
    basename: messages
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      acks: all
  batch:
    job:
      enabled: false

server:
  port: 4002
  servlet:
    context-path: /invoice

invoice:
  scheduler-cron: "0 0 0 25 * ?"
  zone: Asia/Tokyo
  user-notification-topic-name: user-notification-topic
  outbox-scheduler-fixed-rate: 10000
  outbox-scheduler-initial-delay: 10000
